### ISSUE TITLE
What are RGB main properties?

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/FAQ#2]
* Confidentiality
* Safety
* Scalability
* No bitcoin blockchain congestion
* Future-ready without hardforks
* Higher censorship-resistance than in bitcoin: miners do not see that there is something going on with assets in transactions

**Comment by dr-orlovsky** [comment]
I forgot about
* higher censorship-resistance than in bitcoin: miners do not see that there is something going on with assets in transactions

**Comment by UkolovaOlga** [comment]
Thanks, added

> I forgot about
> 
> * higher censorship-resistance than in bitcoin: miners do not see that there is something going on with assets in transactions

**Comment by UkolovaOlga** [comment]
Added to the FAQ
