### ISSUE TITLE
RGB-21: Feedback on Ticker question

### ISSUE THREAD

**Issue by ctramount** [LNP-BP/FAQ#28]
Ethereum uses ticker-based "Collections" for their NFTs architecture. From my understanding, minted ERC721 tokens must be minted to a collection. They're nice for organizational purposes e.g., artists can mint all NFTs to their personal collection making their entire portfolio easy to query. However, collections create friction because they are expensive to mint ($10-30 USD at current gas levels). 

It seems a large part of Rarible's success can be attributed to allowing issuers to mint to their collection "RARI" (https://app.rarible.com/create/erc721) with minimal gas fees, whereas Opensea required issuers to mint a collection (They've just recently launched a product to bypass this: https://opensea.io/storefronts-staging).

In sum, collections are worthwhile as long as they can be minted with minimal fees. An optimization feature that's not available on Ethereum could be to allow Collections to be shared among multiple issuers. An example in which this can be useful is with art collectives and collaborations.

**Comment by UkolovaOlga** [comment]
Feedback has been moved to the corresponding discussion https://github.com/LNP-BP/LNPBPs/discussions/77?converting=1#discussioncomment-200697
