### ISSUE TITLE
RGB-21 Feedback: Engraving & Reserves

### ISSUE THREAD

**Issue by ctramount** [LNP-BP/FAQ#29]
From my understanding of the proposed engraving and reserve features, both open the potential to interesting use cases. 

Engraving sounds like a native way to enable [async.art](url) 's model of minting "master NFTs" which are composed of several "layer NFTs". Layer NFTs can be modified by owners which in turn alters the master NFT. The ability to collaborate on a single work seems to have found traction among the NFT art community - async.art recently set a record with their $120K sale for a single work (https://www.kogocrypto.com/micah-johnsons-nft-artwork-sells-for-120000-on-async-art/).

The reserve feature could be immediately useful to Scarce.City. Our first planned NFT use case is to associate tokens with physical art as a tokenized certificate of authenticity. Reserves could allow us to automatically and trustlessly transfer the token to the buyer of the physical work when they make a payment to a designated Bitcoin address.

I think these use cases are just scratching the surface of what these features enable.

**Comment by UkolovaOlga** [comment]
The issue has been migrated to the Discussions tab https://github.com/LNP-BP/LNPBPs/discussions/80
