### ISSUE TITLE
How does the LNP Node differ from other LN nodes implementations, like Eclair, C-lightning and LND?

### ISSUE THREAD

**Issue by UkolovaOlga** [LNP-BP/FAQ#31]
It is not different in terms of implementing the Lightning Network specification, but it is very different in its architecture. It is created with the idea that we need an implementation that is flexible and that would allow you to easily add very complex modifications of the current Lightning Network so that you could get, for example, PTLC and DLC running, play with Taproot or channel factories. Due to a very rigid architecture of other LN nodes, any experiments become very complex and hard, often leading to the need of rewriting huge parts of nodes implementations in order to do it. With the LNP Node it is fairly easy to do (compared to rewriting existing nodes or writing your own from scratch).

**Comment by dr-orlovsky** [comment]
Also forgot>
- no JSON RPC APIs; uses only ZMQ version based on the protocol similar to LN networking itself ("internet2 api")
- the only node with mobile SDK maintained by developer
- suitable for scalable cloud setup/dockerization across many server instances for high-load setup
- the only node today supporting RGB

**Comment by UkolovaOlga** [comment]
Moved to discussions in the current repo
